# Generated by Django 5.1 on 2024-08-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_subscriptions_groups_subscriptions_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptions",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
