# Generated by Django 5.1 on 2024-09-07 06:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0007_subscriptionsprice_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptions",
            name="featured",
            field=models.BooleanField(
                default=True,
                help_text="Featured on Django Pricing page, doesn't affect stripe things",
            ),
        ),
        migrations.AddField(
            model_name="subscriptions",
            name="order",
            field=models.IntegerField(
                default=-1, help_text="Odering on django pricing page"
            ),
        ),
        migrations.AddField(
            model_name="subscriptions",
            name="price",
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=10),
        ),
        migrations.AddField(
            model_name="subscriptions",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscriptions",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
