# Generated by Django 5.1 on 2024-09-07 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0008_subscriptions_featured_subscriptions_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptions",
            name="price",
        ),
    ]
