# Generated by Django 5.1 on 2024-09-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0010_alter_subscriptionsprice_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionsprice",
            name="features",
            field=models.TextField(
                blank=True,
                help_text="Features for Subscription seperated by new line",
                null=True,
            ),
        ),
    ]
