# Generated by Django 5.1 on 2024-09-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0011_subscriptionsprice_features"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionsprice",
            name="features",
        ),
        migrations.AddField(
            model_name="subscriptions",
            name="features",
            field=models.TextField(
                blank=True,
                help_text="Features for Subscription seperated by new line",
                null=True,
            ),
        ),
    ]
